#include "stdafx.h"
#include "aCoin.h"

using namespace std;

// constructor for the coin.
aCoin::aCoin(int low, int high, int iter) : aRandomNumberGenerator(low, high, iter)
{
	//setRange(low, high);
	//validateIterations(iter);
}

// flips the coin and returns the face generated by the 
// randomNumberGenerator!!!!!!
int aCoin::flipCoin()
{
	return aRandomNumberGenerator::generateNumber();
}

// from last project...
/*
// sets the range for the object
void aCoin::setRange(int low, int high)
{
	lower = low;
	upper = high;
}

// gets the lower boundry of the die for the object
int aCoin::getRangeLow() const
{
	return lower;
}

// gets the upper boundry of the die for the object
int aCoin::getRangeHigh() const
{
	return upper;
}

// sets the iterator for the object
void aCoin::setIterator(int iters)
{
	iterations = iters;
}

// validates the amount of times the user wants to flip the coin.
void aCoin::validateIterations(int iter)
{
	while(iter <= 0)
	{
		cout << "Uh oh, your iterator isn't correct...\nPlease enter the amount again: ";
		cin >> iter;
	}
	setIterator(iter);
}

// gets the number of times the user wants to flip the coin for the object.
int aCoin::getIterations() const
{
	return iterations;
}

// implements throwing the coin the amount of times the user puts in
int aCoin::flipCoin()
{
	int face;
	generateCoin.validateRange(getRangeLow(), getRangeHigh());
	face = generateCoin.generateNumber();
	return face;
}
*/