#include "stdafx.h"
#include "Coin.h"

using namespace std;

// Constructor for the coin.
Coin::Coin(int low, int high, int iter) : RandomNumberGenerator(low = 0, high = 1, iter = 6000)
{
	setRange(low, high);
}

// Flips the coin and returns the number (zero or one) generated by
// RandomNumberGenerator.
int Coin::generateNumber()
{
	return RandomNumberGenerator::generateNumber();
}