#include "stdafx.h"
#include "Die.h"

using namespace std;

// Constructor for the die.
Die::Die(int low, int high, int iter) : RandomNumberGenerator(low = 1, high = 6, iter = 6000)
{
	setRange(low, high);
}

// Throws the die and returns the number (1 through 6) generated by the 
// randomNumberGenerator.
int Die::generateNumber()
{
	return RandomNumberGenerator::generateNumber();
}