#include "stdafx.h"
#include "aCoin.h"

using namespace std;

// Constructor for the coin.
aCoin::aCoin(int low, int high, int iter) : aRandomNumberGenerator(low = 0, high = 1, iter = 6000)
{
	setRange(low, high);
}

// Flips the coin and returns the number (zero or one) generated by
// aRandomNumberGenerator.
int aCoin::flipCoin()
{
	return generateNumber();
}