#include "stdafx.h"
#include "aDie.h"

using namespace std;

// Constructor for the die.
aDie::aDie(int low, int high, int iter) : aRandomNumberGenerator(low = 1, high = 6, iter = 6000)
{
	setRange(low, high);
}

// Throws the die and returns the number (1 through 6) generated by the 
// randomNumberGenerator.
int aDie::throwDie()
{
	return generateNumber();
}